apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: rag-api-access
  namespace: ai-agent-ns
spec:
  hosts:
    - rag-orchestrator.c-321a6c0.stage.kyma.ondemand.com
  service:
    name: rag-orchestrator
    port: 8000
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /query
      methods:
        - POST
      noAuth: true
    - path: /metrics
      methods:
        - GET
      noAuth: true 